### ISSUE TITLE
Pinned tabs have a transparent background

### ISSUE THREAD

**Issue by abidurr** [perragnar/february-frost#2]
See picture below. Using VS Code version 1.49 on MacOS Catalina 10.15.6.

<img width="286" alt="Screen Shot 2020-09-11 at 1 35 41 PM" src="https://user-images.githubusercontent.com/5675070/92956466-ebd06000-f434-11ea-9d0e-92990515506f.png">

Love the theme by the way! <3

**Comment by perragnar** [comment]
Hi! I', glad you like the theme.

Thanks for reporting the issue. I have just fixed the background color for inactive tabs and published an update to the Markeplace. I hope this fixes the issue with the transparent tabs.
